brew "coreutils"
brew "hugo"
brew "shellcheck"
brew "mas"
brew "asdf"

cask "adguard"
cask "discord"
cask "firefox"
cask "gnucash"
cask "microsoft-edge"
cask "microsoft-office"
cask "notion"
cask "openinterminal"
cask "rancher"
cask "rectangle"
cask "slack"
cask "spotify"
cask "surfshark"
cask "thunderbird@esr"
cask "visual-studio-code"
cask "zoom"

mas "Bitwarden", id: 1352778147
mas "Keepa - Price Tracker", id: 1533805339
mas "Microsoft To Do",id: 1274495053
mas "Mia Translate", id: 1500605326
