tap "homebrew/cask-versions"
tap "homebrew/cask-drivers"

brew "coreutils"
brew "curl"
brew "wget"
brew "git"
brew "tree"
brew "gpg"
brew "pinentry-mac"
brew "gnu-tar"
brew "pixz"
brew "gnuplot"
brew "imagemagick"
brew "qpdf"
brew "hugo"
brew "shellcheck"
brew "mas"
brew "asdf"

cask "adguard"
cask "adobe-acrobat-reader"
cask "arduino"
cask "authy"
cask "blackhole-16ch"
cask "clip-studio-paint"
cask "coteditor"
cask "cryptomator"
cask "cyberduck"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "gpg-suite-no-mail"
cask "iina"
cask "inkscape"
cask "mactex-no-gui"
cask "microsoft-word"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-teams"
cask "notion"
cask "onedrive"
cask "openinterminal"
cask "parallels"
cask "parallels-toolbox"
cask "spotify"
cask "thunderbird"
cask "visual-studio-code"
cask "wacom-tablet"
cask "yubico-yubikey-manager"
cask "zoom"

mas "Bitwarden", id: 1352778147
mas "Keepa - Price Tracker", id: 1533805339
mas "Microsoft OneNote", id: 784801555
mas "Microsoft To Do",id: 1274495053
mas "Mia Translate", id: 1500605326
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Telephone", id: 406825478
mas "Vectornator: Design Software", id: 1219074514